server:
  port: 3000
spring:
  application:
    name: order-service-grpc
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-grpc
    username: onceptual_user
    password: onceptual
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect